[package]
name = "elfo-core"
version = "0.1.14"
description = "The core of the system"
authors = ["Paul Loyd <pavelko95@gmail.com>"]
edition = "2018"
license = "MIT"

[features]
test-util = ["tokio/test-util"]
dumping = []

[dependencies]
elfo-macros = { version = "0.1", path = "../elfo-macros" }
elfo-utils = { version = "0.1", path = "../elfo-utils" }

# TODO: replace `tokio` with `agnostik`.
tokio = { version = "1.5", features = ["rt", "sync", "time"] }
tokio-util = "0.6.7"
sharded-slab = "0.1.1"
futures-intrusive = "0.4.0"
parking_lot = "0.11.1"
smallbox = "0.8.0"
serde = { version = "1.0.120", features = ["derive", "rc"] }
derive_more = "0.99.11"
tracing = "0.1.25"
futures = "0.3.12"
static_assertions = "1.1.0"
dashmap = "4.0.2"
fxhash = "0.2.1"
linkme = "0.2.4"
smallvec = { version = "1.6.1", features = ["union"] }
slotmap = "1.0.2"
serde-value = "0.7.0"
arc-swap = "1.2.0"
erased-serde = "0.3.16"

[dev-dependencies]
anyhow = "1.0.40"
libc = "0.2.97"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.2.15"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
