[package]
name = "elfo"
version = "0.1.18"
description = "Your next actor system"
keywords = ["actor", "distributed", "tokio"]
authors = ["Paul Loyd <pavelko95@gmail.com>"]
repository = "https://github.com/elfo-rs/elfo"
license = "MIT"
readme = "../README.md"
edition = "2018"

[[test]]
name = "test"
path = "examples/test.rs"
required-features = ["test-util"]

[[example]]
name = "usage"
path = "examples/usage.rs"
required-features = ["full"]

[[example]]
name = "streams"
path = "examples/streams.rs"
required-features = ["full"]

# TODO: ugly, duplicate.
[[example]]
name = "test"
path = "examples/test.rs"
required-features = ["test-util"]

[[test]]
name = "msg_macro"
path = "tests/msg_macro.rs"
required-features = ["test-util"]

[[bench]]
name = "round_trip"
harness = false
required-features = ["full"]

[features]
full = ["elfo-configurer", "elfo-logger", "elfo-dumper"]
test-util = ["elfo-test", "elfo-core/test-util"]

[dependencies]
elfo-core = { version = "0.1.14", path = "../elfo-core" }
elfo-macros = { version = "0.1.7", path = "../elfo-macros" }
elfo-test = { version = "0.1.12", path = "../elfo-test", optional = true }
elfo-configurer = { version = "0.1.5", path = "../elfo-configurer", optional = true }
elfo-logger = { version = "0.1.1", path = "../elfo-logger", optional = true }
elfo-dumper = { version = "0.1.0", path = "../elfo-dumper", optional = true }

[dev-dependencies]
elfo-test = { version = "0.1.12", path = "../elfo-test" }

anyhow = "1.0.38"
futures = "0.3.12"
derive_more = "0.99.11"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.25"
tracing-subscriber = "0.2.15"
serde = { version = "1.0.120", features = ["derive"] }
toml = "0.5.8"
humantime-serde = "1"
criterion = "0.3.4"
static_assertions = "1.1.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
